version: "3.8"

services:
  # Alice is the Voting Authority
  # Alice doesn't validate any blocks -> just runs a full node
  alice:
    container_name: alice
    image: ghcr.io/provotum/provotum-mixnet:latest
    command: --chain=local --name Alice --base-path /tmp/alice --port 30333 --ws-port 9944 --rpc-port 9933 --execution Native
    network_mode: host
    # network_mode: bridge
    # ports: # HOST_PORT:CONTAINER_PORT
    #   - 9944:9944
    #   - 30333:30333
    #   - 9933:9933

  # Bob is a Sealer (Voting) and a Proof-Of-Authority Validator
  # Bob authors and validates blocks
  bob:
    container_name: bob
    image: ghcr.io/provotum/provotum-mixnet:latest
    command: --chain=local --bob --validator --base-path /tmp/bob --port 30334 --ws-port 9945 --rpc-port 9934 --execution Native
    network_mode: host
    # network_mode: bridge
    # ports:
    #   - 9945:9945
    #   - 30334:30334
    #   - 9934:9934

  # Charlie is a Sealer (Voting) and a Proof-Of-Authority Validator
  # Charlie authors and validates blocks
  charlie:
    container_name: charlie
    image: ghcr.io/provotum/provotum-mixnet:latest
    command: --chain=local --charlie --validator --base-path /tmp/charlie --port 30335 --ws-port 9946 --rpc-port 9935 --execution Native
    network_mode: host
    # ports:
    #   - 9946:9946
    #   - 30335:30335
    #   - 9935:9935

  # Randomizer is a simple web service to re-encrypt the voter's ballots
  randomizer:
    container_name: charliee
    image: ghcr.io/provotum/provotum-mixnet-randomizer:latest
    network_mode: host

  api_cli:
    container_name: api
    image: sumsumcity/api_cli:latest
    network_mode: host
    # ports:
    #   - 4000:4000

  mongoDB:
    image: mongo
    network_mode: host
    # ports:
    #  - "27017:27017"

  va:
    container_name: va_gui
    image: sumsumcity/gui_va:latest
    ports:
      - "3000:3000"
    environment:
      - SEALER=alice
    stdin_open: true
    tty: true

  sealer1:
    container_name: sealer_gui_bob
    image: sumsumcity/gui_sealer:latest
    ports:
      - "3001:3001"
    environment:
      - SEALER=bob
      - PORT=3001
    stdin_open: true
    tty: true

  sealer2:
    container_name: sealer_gui_charlie
    image: sumsumcity/gui_sealer:latest
    ports:
      - "3002:3002"
    environment:
      - SEALER=charlie
      - PORT=3002
    stdin_open: true
    tty: true

  voter:
    container_name: voter_gui
    image: sumsumcity/gui_voter
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

